[command]
bin = "git"

[deny]
args = ["--upload-pack", "-u", "--config", "-c", "--exec-path", "--template"]

[env]
strip = ["GIT_SSH_COMMAND", "GIT_CONFIG", "GIT_CONFIG_GLOBAL", "GIT_CONFIG_PARAMETERS", "GIT_ATTR_SOURCE", "GIT_CONFIG_COUNT"]
set = { GIT_CONFIG_NOSYSTEM = "1", GIT_CONFIG_COUNT = "1", GIT_CONFIG_KEY_0 = "core.hooksPath", GIT_CONFIG_VALUE_0 = "/dev/null" }

[exec]
concurrent = true
