[command]
bin = "aws"

[deny]
args = ["terminate-instances", "delete-db-instance", "delete-user", "delete-role", "delete-bucket"]

[env]
strip = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]

[exec]
concurrent = true
