[command]
bin = "docker"

[deny]
args = [
    "--privileged",
    "-v=/*:*",
    "--volume=/*:*",
    "-v=*docker.sock*",
    "--volume=*docker.sock*",
    "--pid=host",
    "--net=host",
    "--network=host",
    "--ipc=host",
    "--cap-add=ALL",
    "--security-opt=apparmor:unconfined",
]

[env]
strip = ["DOCKER_HOST", "DOCKER_TLS_VERIFY", "DOCKER_CERT_PATH"]

[exec]
concurrent = true
